# syntax
# - http://symfony.com/doc/current/components/yaml/yaml_format.html
# please check validate
# - http://codebeautify.org/yaml-validator
# - http://yaml-online-parser.appspot.com

KR:
    skin: 'halloween'
TW: 
    skin: ''
CN: 
    skin: ''
